
### Requisição para raiz

GET http://localhost:5089

### lISTAR TODOS OS PRODUTOS

GET http://localhost:5089/api/produto/listar

### Requisição para a funcionalidade com POST

POST http://localhost:5089/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Mouse",
    "quantidade" : 123, 
    "preco" : 85.5
}

### Buscar PRODUTOS por nome
GET http://localhost:5089/api/produto/buscar/Monitor 24%22