
### Requisição para raiz

GET http://localhost:5089

### lISTAR TODOS OS PRODUTOS

GET http://localhost:5089/api/produto/listar

### Requisição para a funcionalidade com POST

POST http://localhost:5089/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Placa de Vídeo RTX 4090",
    "quantidade" : 1, 
    "descricao" : "Eletronico",
    "preco" : 85.5
}

### Buscar PRODUTOS por id
GET http://localhost:5089/api/produto/buscar/038ab2d3-b7dd-4f5b-bcbc-3ef78a9ae427

### Deletar PRODUTOS por id
DELETE http://localhost:5089/api/produto/remover/2f452726-7292-4c1c-bc6f-4a940dd6dc52

### Alterar PRODUTOS por id
PATCH http://localhost:5089/api/produto/alterar/f412f088-265e-41d7-ae13-f63df9e9ad93
Content-Type: application/json

{
    "nome" : "Placa de Vídeo RTX 4090",
    "quantidade" : 2, 
    "preco" : 90.5
}